spring:
  config:
    activate:
      on-profile: develop

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show-sql: true

server:
  port: 8080

#jwt
jwt:
  secret: 
  issuer: sixsense
  accessTime: 900000
  refreshTime: 2592000000

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
